import React from 'react';

export type TutorRegister =
  | 'foundational'        // topology / linalg / prob / calculus — intuition-first
  | 'measure-theoretic'   // stochastics — σ-algebras, Itô, filtrations
  | 'operator-theoretic'  // signal/spectrum — Hilbert spaces, operators
  | 'information'         // info-geometry — statistical manifolds, KL, Fisher
  | 'scaling'             // scaling & chaos — power laws, RMT, Lyapunov
  | 'architectural';      // LLM infrastructure — tie math to transformer code

export const TRACK_REGISTER: Record<string, TutorRegister> = {
  topology: 'foundational',
  linearalgebra: 'foundational',
  probability: 'foundational',
  calculus: 'foundational',
  stochastics: 'measure-theoretic',
  signal: 'operator-theoretic',
  infogeo: 'information',
  scaling: 'scaling',
  llminfra: 'architectural',
};

export interface Lesson {
  id: string;          // e.g. "topology-1-1"
  track: string;       // e.g. "topology"
  trackLabel: string;
  index: number;       // 1, 2, 3 within track
  title: string;
  description: string;
  coreIdea: string;    // one sentence for tutor prompt
  mbdBridge: string;   // one sentence for tutor prompt
  llmHook?: string;    // optional: where this concept lives in LLM architecture
  component: React.LazyExoticComponent<any>;
}

export const LESSONS: Lesson[] = [
  {
    id: 'topology-1-1',
    track: 'topology',
    trackLabel: 'Topology & Geometry',
    index: 1,
    title: 'Spaces & Neighborhoods',
    description: 'What it means to be "close" without coordinates',
    coreIdea: 'A space can be defined entirely by which points are considered close to each other (neighborhoods), without needing a grid or distances.',
    mbdBridge: 'The MBD state space B(t) lives on a manifold. Neighborhoods define what states are "reachable" from a given baseline without a discontinuous leap.',
    component: React.lazy(() => import('../lessons/topology/Lesson1_1')),
  },
  {
    id: 'topology-1-2',
    track: 'topology',
    trackLabel: 'Topology & Geometry',
    index: 2,
    title: 'Continuity Without Numbers',
    description: 'Deformation, homeomorphism, the coffee-cup/donut',
    coreIdea: 'Continuous transformations stretch and bend space without tearing or gluing.',
    mbdBridge: 'As the baseline B(t) adapts, the cognitive "shape" of the world continuously deforms. Tearing would mean trauma or discontinuous identity shifts.',
    component: React.lazy(() => import('../lessons/topology/Lesson1_2')),
  },
  {
    id: 'topology-1-3',
    track: 'topology',
    trackLabel: 'Topology & Geometry',
    index: 3,
    title: 'Manifolds & Tangent Spaces',
    description: 'Why local flatness enables global curvature',
    coreIdea: 'Curved spaces look flat if you zoom in enough, allowing us to use linear algebra locally.',
    mbdBridge: 'The update rule B(t+1) = B(t) + Î»(I âˆ’ B(t)) operates in the tangent space of the current baseline. Every baseline provides a local flat perspective on a globally complex reality.',
    component: React.lazy(() => import('../lessons/topology/Lesson1_3')),
  },
  {
    id: 'linearalgebra-2-1',
    track: 'linearalgebra',
    trackLabel: 'Linear Algebra',
    index: 1,
    title: 'Vectors as Arrows in Space',
    description: 'Geometric intuition before coordinates',
    coreIdea: 'Vectors represent movements or forces in space, independent of any arbitrary coordinate system we impose on them.',
    mbdBridge: 'The term (I - B(t)) is the fundamental variation vector: the exact direction and magnitude needed to pull the baseline toward the ideal/input.',
    component: React.lazy(() => import('../lessons/linearalgebra/Lesson2_1')),
  },
  {
    id: 'linearalgebra-2-2',
    track: 'linearalgebra',
    trackLabel: 'Linear Algebra',
    index: 2,
    title: 'Eigenvectors: The Skeleton',
    description: 'What a transformation "wants to do"',
    coreIdea: 'An eigenvector is a direction that is only stretched, not rotated, by a transformation. They reveal the "grain" of the space.',
    mbdBridge: 'In a multi-dimensional MBD framework, the eigenvectors of the coupling matrix K determine which combinations of baselines attract each other strongest.',
    component: React.lazy(() => import('../lessons/linearalgebra/Lesson2_2')),
  },
  {
    id: 'linearalgebra-2-3',
    track: 'linearalgebra',
    trackLabel: 'Linear Algebra',
    index: 3,
    title: 'The Gradient as a Covector',
    description: 'Why âˆ‡f points uphill and lives in dual space',
    coreIdea: 'The gradient isn\'t just an arrow; it\'s a set of contour lines waiting to measure the steepness of any passing vector.',
    mbdBridge: 'The update rule B(t+1) = B(t) + Î»(I âˆ’ B(t)) is gradient descent on the quadratic error landscape between expectation and reality.',
    component: React.lazy(() => import('../lessons/linearalgebra/Lesson2_3')),
  },
  {
    id: 'probability-3-1',
    track: 'probability',
    trackLabel: 'Probability & Information',
    index: 1,
    title: 'Probability as Geometry',
    description: 'Distributions as points on a simplex',
    coreIdea: 'A set of probabilities must sum to 1, constraining them to a flat geometric surface called a simplex.',
    mbdBridge: 'A probabilistic baseline B(t) represents a distribution over expected states. MBD dynamics move this distribution across the simplex.',
    component: React.lazy(() => import('../lessons/probability/Lesson3_1')),
  },
  {
    id: 'probability-3-2',
    track: 'probability',
    trackLabel: 'Probability & Information',
    index: 2,
    title: 'Entropy & Information',
    description: 'Uncertainty as a measure of spread',
    coreIdea: 'Entropy measures how spread out a distribution is. High entropy means fewer assumptions and more surprise.',
    mbdBridge: 'A narrow, low-entropy baseline is rigid and "surprised" by many inputs. A high-entropy baseline is flexible but holds little specific expectation.',
    component: React.lazy(() => import('../lessons/probability/Lesson3_2')),
  },
  {
    id: 'probability-3-3',
    track: 'probability',
    trackLabel: 'Probability & Information',
    index: 3,
    title: 'Bayes as Update on a Prior',
    description: 'Belief revision as vector operation',
    coreIdea: 'Bayes theorem multiplies what you believed before by what you just saw to get what you should believe now.',
    mbdBridge: 'MBD perturbation events are Bayesian evidence. The new baseline B(t+1) is the posterior, continuously revising the prior B(t) weighted by the evidence I.',
    component: React.lazy(() => import('../lessons/probability/Lesson3_3')),
  },
  {
    id: 'calculus-4-1',
    track: 'calculus',
    trackLabel: 'Calculus of Variation',
    index: 1,
    title: 'Derivatives as Linear Approximation',
    description: 'The best linear map at a point',
    coreIdea: 'A derivative replaces a wiggly, complicated curve with a straight line that traces its immediate path.',
    mbdBridge: 'When the baseline changes infinitesimally, the local change is a linear mapping from reality\'s perturbation into the baseline\'s geometry.',
    component: React.lazy(() => import('../lessons/calculus/Lesson4_1')),
  },
  {
    id: 'calculus-4-2',
    track: 'calculus',
    trackLabel: 'Calculus of Variation',
    index: 2,
    title: 'Differential Equations as Vector Fields',
    description: 'Solutions as flow lines',
    coreIdea: 'A differential equation assigns a little arrow to every point in space. Solving it means dropping a leaf and watching where the current takes it.',
    mbdBridge: 'The continuous-time formulation of MBD is the differential equation dB/dt = Î»(I(t) - B(t)), defining a flow field tracking the moving ideal.',
    component: React.lazy(() => import('../lessons/calculus/Lesson4_2')),
  },
  {
    id: 'calculus-4-3',
    track: 'calculus',
    trackLabel: 'Calculus of Variation',
    index: 3,
    title: 'The Natural Gradient',
    description: 'Why steepest descent depends on geometry',
    coreIdea: 'The direction of steepest descent changes if the underlying space is warped or curved, like running down a rocky hill.',
    mbdBridge: 'The standard gradient ignores the curvature of the baseline manifold. The Fisher-weighted natural gradient ensures MBD respects the information geometry of the mind.',
    component: React.lazy(() => import('../lessons/calculus/Lesson4_3')),
  },

  // ─────────────────────────────────────────────────────────────────
  // TRACK 5 — STOCHASTICS: belief updating, noise, diffusion models
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'stochastics-5-1',
    track: 'stochastics',
    trackLabel: 'Stochastics',
    index: 1,
    title: 'σ-Algebras & Filtrations',
    description: 'The measurable structure of random information',
    coreIdea: 'A σ-algebra encodes "what questions you can ask" at a given time. A filtration is a growing σ-algebra — the flow of information itself.',
    mbdBridge: 'The baseline B(t) is measurable with respect to the filtration ℱ_t: at each moment, only the history up to t is available to update it.',
    llmHook: 'Causal attention masking is a discrete filtration: token t may only attend to tokens ≤ t.',
    component: React.lazy(() => import('../lessons/stochastics/Lesson5_1')),
  },
  {
    id: 'stochastics-5-2',
    track: 'stochastics',
    trackLabel: 'Stochastics',
    index: 2,
    title: 'The Kalman Filter',
    description: 'Optimal linear belief under Gaussian noise',
    coreIdea: 'The Kalman filter is recursive Bayesian inference for linear-Gaussian state-space models — predict, observe, Kalman-gain-weighted correction.',
    mbdBridge: 'MBD\'s baseline update B(t+1) = B(t) + λ(I − B(t)) is the scalar-constant-gain special case of a Kalman filter with fixed signal-to-noise ratio.',
    llmHook: 'Mamba and S4 are continuous-time linear state-space models — Kalman filtering with learned dynamics replacing quadratic attention.',
    component: React.lazy(() => import('../lessons/stochastics/Lesson5_2')),
  },
  {
    id: 'stochastics-5-3',
    track: 'stochastics',
    trackLabel: 'Stochastics',
    index: 3,
    title: 'Brownian Motion & Itô Calculus',
    description: 'Differentiating the non-differentiable',
    coreIdea: 'Brownian motion is nowhere differentiable but has quadratic variation t, giving rise to the Itô correction (dB_t)² = dt.',
    mbdBridge: 'Stochastic baselines dB(t) = λ(I−B)dt + σdW_t allow baselines to wander: a noisy mind is mathematically required for exploration.',
    llmHook: 'Every diffusion model\'s forward process is an SDE; every reverse-time sample trajectory is an Itô integral.',
    component: React.lazy(() => import('../lessons/stochastics/Lesson5_3')),
  },
  {
    id: 'stochastics-5-4',
    track: 'stochastics',
    trackLabel: 'Stochastics',
    index: 4,
    title: 'Langevin Dynamics',
    description: 'Gradient descent plus thermal noise',
    coreIdea: 'dX = −∇U(X)dt + √(2/β) dW samples the Gibbs distribution p(x) ∝ e^{−β U(x)} as t → ∞. Gradient descent is Langevin at β = ∞.',
    mbdBridge: 'A finite-temperature MBD mind explores baseline space ergodically, not just optimally — creativity requires β < ∞.',
    llmHook: 'Stochastic Gradient Langevin Dynamics (SGLD) is Bayesian deep learning; every SGD step at finite batch size is approximately Langevin.',
    component: React.lazy(() => import('../lessons/stochastics/Lesson5_4')),
  },
  {
    id: 'stochastics-5-5',
    track: 'stochastics',
    trackLabel: 'Stochastics',
    index: 5,
    title: 'Score Matching',
    description: '∇ log p(x) without knowing p(x)',
    coreIdea: 'The score ∇ₓ log p(x) can be learned without computing the partition function, via denoising or sliced score matching.',
    mbdBridge: 'The MBD pull term λ(I−B) is a score — the gradient of the log-density of a Gaussian prior centered at the ideal I.',
    llmHook: 'Score matching IS the training objective of diffusion LLMs and all modern diffusion image models.',
    component: React.lazy(() => import('../lessons/stochastics/Lesson5_5')),
  },
  {
    id: 'stochastics-5-6',
    track: 'stochastics',
    trackLabel: 'Stochastics',
    index: 6,
    title: 'Reverse-Time Diffusion',
    description: 'Anderson\'s theorem: noise → signal',
    coreIdea: 'Anderson (1982) showed every forward SDE has a reverse SDE that denoises. The reverse drift is forward drift minus score ∇log p_t.',
    mbdBridge: 'MBD relaxation toward I is the reverse-time process of a baseline that diffused outward; memory is a denoising trajectory.',
    llmHook: 'The exact mathematical foundation of Stable Diffusion, DALL·E, Sora, and diffusion-language-model sampling.',
    component: React.lazy(() => import('../lessons/stochastics/Lesson5_6')),
  },

  // ─────────────────────────────────────────────────────────────────
  // TRACK 6 — SIGNAL & SPECTRUM: Hilbert spaces, kernels, RoPE
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'signal-6-1',
    track: 'signal',
    trackLabel: 'Signal & Spectrum',
    index: 1,
    title: 'Hilbert Spaces & Inner Products',
    description: 'Geometry in infinite dimensions',
    coreIdea: 'A Hilbert space is a complete inner-product space: every Cauchy sequence converges. It extends Euclidean geometry to function spaces.',
    mbdBridge: 'The space of possible baselines B(·) is a Hilbert space L²; the pull term is an L²-projection onto the ideal.',
    llmHook: 'Embedding spaces ARE Hilbert spaces; cosine similarity IS the inner product; attention is a projection operator.',
    component: React.lazy(() => import('../lessons/signal/Lesson6_1')),
  },
  {
    id: 'signal-6-2',
    track: 'signal',
    trackLabel: 'Signal & Spectrum',
    index: 2,
    title: 'Fourier Decomposition',
    description: 'Every function is a sum of rotations',
    coreIdea: 'The Fourier transform decomposes f ∈ L²(ℝ) into orthogonal frequency components: f(x) = ∫ f̂(ξ) e^{2πiξx} dξ.',
    mbdBridge: 'Periodic perturbations on MBD dynamics decompose into frequency responses — the baseline acts as a low-pass filter.',
    llmHook: 'Fourier features are the mathematical ancestor of RoPE and all sinusoidal position encodings.',
    component: React.lazy(() => import('../lessons/signal/Lesson6_2')),
  },
  {
    id: 'signal-6-3',
    track: 'signal',
    trackLabel: 'Signal & Spectrum',
    index: 3,
    title: 'Rotary Positional Embeddings',
    description: 'Position as rotation in complex pairs',
    coreIdea: 'RoPE rotates each query/key pair in ℝ² by an angle proportional to position — so that q(m)·k(n) depends only on m−n.',
    mbdBridge: 'Relative time in MBD is what matters for coupling: a rotation-based encoding makes dynamics translation-equivariant.',
    llmHook: 'RoPE is used in Llama, Mistral, Qwen, DeepSeek — the dominant position encoding in modern open-weight LLMs.',
    component: React.lazy(() => import('../lessons/signal/Lesson6_3')),
  },
  {
    id: 'signal-6-4',
    track: 'signal',
    trackLabel: 'Signal & Spectrum',
    index: 4,
    title: 'Kernels & RKHS',
    description: 'Similarity functions that are secretly inner products',
    coreIdea: 'A positive-definite kernel k(x,y) induces a Reproducing Kernel Hilbert Space where k(x,·) is the evaluation functional at x.',
    mbdBridge: 'The coupling K between baselines is a kernel on baseline-space; the RKHS is the space of all possible cognitive states.',
    llmHook: 'Attention softmax(QKᵀ/√d)V is a kernel smoother: the softmax is a normalized Gaussian-ish kernel over queries.',
    component: React.lazy(() => import('../lessons/signal/Lesson6_4')),
  },
  {
    id: 'signal-6-5',
    track: 'signal',
    trackLabel: 'Signal & Spectrum',
    index: 5,
    title: 'Gaussian Processes',
    description: 'Distributions over functions',
    coreIdea: 'A GP is a distribution over functions such that any finite collection {f(x₁),…,f(xₙ)} is jointly Gaussian with covariance k(xᵢ,xⱼ).',
    mbdBridge: 'The uncertainty field over baselines is a GP; observed experiences collapse posterior variance locally.',
    llmHook: 'The Neural Tangent Kernel shows infinitely-wide networks ARE Gaussian Processes during training.',
    component: React.lazy(() => import('../lessons/signal/Lesson6_5')),
  },
  {
    id: 'signal-6-6',
    track: 'signal',
    trackLabel: 'Signal & Spectrum',
    index: 6,
    title: 'Spectral Graph Theory',
    description: 'The Laplacian eigenvalues tell you everything',
    coreIdea: 'The graph Laplacian L = D − A has eigenvalues 0 = λ₀ ≤ λ₁ ≤ …; λ₁ (Fiedler) measures connectivity, λ_max measures bipartiteness.',
    mbdBridge: 'A social fabric simulator graph\'s Laplacian spectrum reveals which agents are tightly coupled vs. bridge nodes.',
    llmHook: 'Graph transformers use Laplacian eigenvectors as positional encodings for non-sequential data.',
    component: React.lazy(() => import('../lessons/signal/Lesson6_6')),
  },

  // ─────────────────────────────────────────────────────────────────
  // TRACK 7 — INFORMATION GEOMETRY: Fisher, natural gradient, OT
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'infogeo-7-1',
    track: 'infogeo',
    trackLabel: 'Information Geometry',
    index: 1,
    title: 'Statistical Manifolds',
    description: 'Distributions as points on a curved manifold',
    coreIdea: 'A parameterized family {p_θ} is a manifold with θ as local coordinates; distance between distributions is NOT Euclidean distance in θ.',
    mbdBridge: 'The space of possible MBD baselines is a statistical manifold; its curvature determines how "steep" it is to shift identity.',
    llmHook: 'Every softmax output layer maps to a point on the probability simplex — a statistical manifold with hyperbolic-like geometry near boundaries.',
    component: React.lazy(() => import('../lessons/infogeo/Lesson7_1')),
  },
  {
    id: 'infogeo-7-2',
    track: 'infogeo',
    trackLabel: 'Information Geometry',
    index: 2,
    title: 'The Fisher Information Metric',
    description: 'The unique invariant Riemannian metric on distributions',
    coreIdea: 'Fisher information I(θ)ᵢⱼ = 𝔼[∂ᵢ log p · ∂ⱼ log p] is the unique metric (up to scale) invariant under reparameterization. Čencov\'s theorem.',
    mbdBridge: 'The sensitivity of the baseline\'s log-likelihood to its parameters IS the Fisher metric — it tells MBD how far a step really is.',
    llmHook: 'Fisher information determines natural gradient, Elastic Weight Consolidation, K-FAC, and second-order optimizers.',
    component: React.lazy(() => import('../lessons/infogeo/Lesson7_2')),
  },
  {
    id: 'infogeo-7-3',
    track: 'infogeo',
    trackLabel: 'Information Geometry',
    index: 3,
    title: 'KL Divergence as a Geodesic',
    description: 'Asymmetric, but geometrically meaningful',
    coreIdea: 'KL(p‖q) is not a metric, but near p ≈ q it equals ½ Fisher-distance². Exponential and mixture families give dual affine connections.',
    mbdBridge: 'MBD update minimizes KL from posterior to a constrained family — the update is a projection in dual-flat geometry.',
    llmHook: 'KL penalties in RLHF (PPO, DPO) pull the policy geodesically toward the reference model — NOT Euclideanly.',
    component: React.lazy(() => import('../lessons/infogeo/Lesson7_3')),
  },
  {
    id: 'infogeo-7-4',
    track: 'infogeo',
    trackLabel: 'Information Geometry',
    index: 4,
    title: 'Exponential Families',
    description: 'The flat coordinate system of statistics',
    coreIdea: 'p(x|θ) = h(x) exp(θᵀT(x) − A(θ)). The log-partition A(θ) is convex; its gradient gives the mean parameters η = ∇A(θ).',
    mbdBridge: 'The baseline distribution, if Gaussian-like, lies in an exponential family; MBD updates correspond to natural-parameter updates.',
    llmHook: 'Softmax output layers ARE exponential families; logits are natural parameters, probabilities are mean parameters, cross-entropy is Bregman divergence.',
    component: React.lazy(() => import('../lessons/infogeo/Lesson7_4')),
  },
  {
    id: 'infogeo-7-5',
    track: 'infogeo',
    trackLabel: 'Information Geometry',
    index: 5,
    title: 'Optimal Transport & Wasserstein',
    description: 'How much work to move one distribution onto another',
    coreIdea: 'W_p(μ,ν) = (inf_γ ∫ ‖x−y‖^p dγ)^{1/p} over couplings γ with marginals μ,ν. Kantorovich-Rubinstein duality gives W₁ as a Lipschitz-function sup.',
    mbdBridge: 'Baseline drift under MBD minimizes a Wasserstein-like cost between B(t) and B(t+1) — the mind moves as little mass as possible.',
    llmHook: 'Flow matching (Rectified Flow, Stable Diffusion 3) trains models to interpolate along W₂-geodesics between noise and data.',
    component: React.lazy(() => import('../lessons/infogeo/Lesson7_5')),
  },
  {
    id: 'infogeo-7-6',
    track: 'infogeo',
    trackLabel: 'Information Geometry',
    index: 6,
    title: 'Sinkhorn & Entropic OT',
    description: 'Softening transport with entropy regularization',
    coreIdea: 'Adding εH(γ) regularization to OT makes the optimum unique and computable by matrix scaling: K = exp(−C/ε), then alternate row/col normalize.',
    mbdBridge: 'Soft alignment between current and ideal baseline is entropic OT — the ε parameter is the temperature of identity resolution.',
    llmHook: 'Sinkhorn attention variants, softmax itself as 1D Sinkhorn, and the entire Flash-Sinkhorn literature.',
    component: React.lazy(() => import('../lessons/infogeo/Lesson7_6')),
  },

  // ─────────────────────────────────────────────────────────────────
  // TRACK 8 — SCALING & CHAOS: fractals, RMT, power laws
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'scaling-8-1',
    track: 'scaling',
    trackLabel: 'Scaling & Chaos',
    index: 1,
    title: 'Self-Similarity & Hausdorff Dimension',
    description: 'Non-integer dimension as a scaling exponent',
    coreIdea: 'dim_H(S) = lim log N(ε) / log(1/ε). The Cantor set has dimension log 2 / log 3 ≈ 0.631 — between point and line.',
    mbdBridge: 'Memory recall patterns show multifractal scaling: the MBD baseline\'s attractor is not smooth.',
    llmHook: 'Loss landscapes of trained networks have fractal structure; scaling laws L(N) ∝ N^{−α} encode this geometry.',
    component: React.lazy(() => import('../lessons/scaling/Lesson8_1')),
  },
  {
    id: 'scaling-8-2',
    track: 'scaling',
    trackLabel: 'Scaling & Chaos',
    index: 2,
    title: 'Power Laws & Heavy Tails',
    description: 'When the mean is infinite',
    coreIdea: 'p(x) ∝ x^{−α}. For α ≤ 2 the variance is infinite; for α ≤ 1 the mean is. CLT fails; Lévy-stable limits take over.',
    mbdBridge: 'Perturbation magnitudes in real life are heavy-tailed — MBD must be robust to α-stable impulses, not Gaussian.',
    llmHook: 'Kaplan and Chinchilla scaling laws: loss vs. compute is a power law. Token frequency (Zipf) is a power law. Attention entropy too.',
    component: React.lazy(() => import('../lessons/scaling/Lesson8_2')),
  },
  {
    id: 'scaling-8-3',
    track: 'scaling',
    trackLabel: 'Scaling & Chaos',
    index: 3,
    title: 'Wigner Semicircle Law',
    description: 'The spectrum of a random symmetric matrix',
    coreIdea: 'For an n×n symmetric matrix with iid entries (variance σ²/n), eigenvalues are distributed as ρ(λ) = (2πσ²)⁻¹√(4σ² − λ²) on [−2σ, 2σ].',
    mbdBridge: 'A random coupling matrix between baselines has predictable spectral radius — large networks self-stabilize spectrally.',
    llmHook: 'Transformer weight initialization (Xavier, He) is chosen so forward-pass Hessian spectrum stays near Wigner — edge of stability.',
    component: React.lazy(() => import('../lessons/scaling/Lesson8_3')),
  },
  {
    id: 'scaling-8-4',
    track: 'scaling',
    trackLabel: 'Scaling & Chaos',
    index: 4,
    title: 'Marchenko–Pastur Law',
    description: 'The spectrum of a random covariance matrix',
    coreIdea: 'For X ∈ ℝ^{n×p} iid with n,p → ∞, p/n → q ∈ (0,1], the eigenvalue density of XᵀX/n is the MP distribution with edges (1±√q)².',
    mbdBridge: 'Empirical covariance of baseline observations has a bulk (noise) and spikes (signal) — MP tells us where the separation lies.',
    llmHook: 'Activation covariance matrices in deep nets follow MP bulks with heavy-tail spike corrections — see Pennington-Worah, Mahoney.',
    component: React.lazy(() => import('../lessons/scaling/Lesson8_4')),
  },
  {
    id: 'scaling-8-5',
    track: 'scaling',
    trackLabel: 'Scaling & Chaos',
    index: 5,
    title: 'Lyapunov Exponents',
    description: 'Quantifying sensitivity to initial conditions',
    coreIdea: 'λ = lim_{t→∞} (1/t) log ‖δx(t)‖/‖δx(0)‖. Positive λ means chaos: exponential separation of nearby trajectories.',
    mbdBridge: 'MBD dynamics with coupling > critical value have positive Lyapunov exponents — small perturbations amplify into identity shifts.',
    llmHook: 'RNN training stability hinges on keeping Lyapunov exponents near zero (edge of chaos). Transformers bypass this via residual streams.',
    component: React.lazy(() => import('../lessons/scaling/Lesson8_5')),
  },
  {
    id: 'scaling-8-6',
    track: 'scaling',
    trackLabel: 'Scaling & Chaos',
    index: 6,
    title: 'The Neural Tangent Kernel',
    description: 'Infinitely wide networks are kernel machines',
    coreIdea: 'As width → ∞, the gradient flow of a neural net is kernel gradient descent with kernel Θ(x,x\') = 𝔼[∇_θ f(x)·∇_θ f(x\')] that is CONSTANT during training.',
    mbdBridge: 'In the NTK limit, MBD over an infinitely-wide baseline network becomes linear filtering against a fixed kernel.',
    llmHook: 'NTK explains why large networks train stably; breaks in finite-width regime where feature learning occurs (μP, Tensor Programs).',
    component: React.lazy(() => import('../lessons/scaling/Lesson8_6')),
  },

  // ─────────────────────────────────────────────────────────────────
  // TRACK 9 — LLM INFRASTRUCTURE: the math inside a transformer
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'llminfra-9-1',
    track: 'llminfra',
    trackLabel: 'LLM Infrastructure',
    index: 1,
    title: 'Attention as Kernel Smoothing',
    description: 'softmax(QKᵀ/√d)V decoded geometrically',
    coreIdea: 'Attention is a Nadaraya-Watson estimator: output(q) = Σ w(q,kᵢ) vᵢ where w is a normalized exponential kernel in query-key space.',
    mbdBridge: 'Every MBD state is a kernel-weighted mixture of remembered ones; attention IS memory retrieval as convex combination.',
    llmHook: 'This IS the core of every transformer. Multi-head = multiple kernels. Flash-attention = clever IO for the same math.',
    component: React.lazy(() => import('../lessons/llminfra/Lesson9_1')),
  },
  {
    id: 'llminfra-9-2',
    track: 'llminfra',
    trackLabel: 'LLM Infrastructure',
    index: 2,
    title: 'Softmax Geometry & Temperature',
    description: 'The log-sum-exp sphere',
    coreIdea: 'Softmax maps ℝⁿ to the open simplex Δⁿ⁻¹ bijectively up to constant shifts. Temperature scales the map\'s sharpness; β → ∞ gives argmax.',
    mbdBridge: 'MBD\'s convex-combination update is softmax-temperature = 1; cold temperatures give rigid attractors, hot give fluid mind.',
    llmHook: 'Sampling temperature, top-k/top-p, logit scaling, mixture-of-experts routing — all live on softmax geometry.',
    component: React.lazy(() => import('../lessons/llminfra/Lesson9_2')),
  },
  {
    id: 'llminfra-9-3',
    track: 'llminfra',
    trackLabel: 'LLM Infrastructure',
    index: 3,
    title: 'Layer Norm & Residual Streams',
    description: 'Why transformers are actually ODE solvers',
    coreIdea: 'x_{ℓ+1} = x_ℓ + f_ℓ(LN(x_ℓ)) is Euler\'s method for dx/dℓ = f(x); LN projects to the unit sphere before every update.',
    mbdBridge: 'The residual stream IS a baseline; each layer is an MBD update pulling toward a learned ideal in normalized space.',
    llmHook: 'Neural ODE interpretation: transformer depth ≈ integration time. Explains why very deep residual nets are stable.',
    component: React.lazy(() => import('../lessons/llminfra/Lesson9_3')),
  },
  {
    id: 'llminfra-9-4',
    track: 'llminfra',
    trackLabel: 'LLM Infrastructure',
    index: 4,
    title: 'Measure Concentration',
    description: 'High dimensions are surprisingly flat',
    coreIdea: 'Lipschitz functions on the n-sphere concentrate exponentially: P(|f − 𝔼f| > t) ≤ 2e^{−nt²/(2L²)}. Most of high-dim space is "equatorial."',
    mbdBridge: 'A high-dim MBD baseline is automatically robust: Lipschitz perturbations have vanishingly small effect per dimension.',
    llmHook: 'Why embeddings work at all. Why dropout regularizes. Why random initialization\'s outputs are nearly constant.',
    component: React.lazy(() => import('../lessons/llminfra/Lesson9_4')),
  },
  {
    id: 'llminfra-9-5',
    track: 'llminfra',
    trackLabel: 'LLM Infrastructure',
    index: 5,
    title: 'Tropical Geometry of ReLU Nets',
    description: 'Piecewise-linear expressivity counts regions',
    coreIdea: 'A ReLU network is a tropical rational function — max-plus algebra. Its decision regions form a polyhedral complex whose cell count is the expressivity.',
    mbdBridge: 'A piecewise-linear baseline can have up to 2^{depth·width} cognitive regimes — far more than parameter count suggests.',
    llmHook: 'Tropical geometry explains ReLU MLP expressivity, upper-bounds GELU activations, informs pruning via cell-counting.',
    component: React.lazy(() => import('../lessons/llminfra/Lesson9_5')),
  },
  {
    id: 'llminfra-9-6',
    track: 'llminfra',
    trackLabel: 'LLM Infrastructure',
    index: 6,
    title: 'Scaling Laws as Critical Phenomena',
    description: 'Loss ∝ compute^{−α} is a phase transition',
    coreIdea: 'Kaplan-Chinchilla power laws L(N,D,C) = L∞ + (N_c/N)^{αN} + (D_c/D)^{αD} resemble critical exponents of a 2nd-order phase transition.',
    mbdBridge: 'Increasing baseline-space dimension past a critical threshold yields qualitatively new cognitive capabilities — emergence as criticality.',
    llmHook: 'The empirical backbone of modern LLM training: Chinchilla-optimal ratios, compute-optimal scaling, emergence thresholds.',
    component: React.lazy(() => import('../lessons/llminfra/Lesson9_6')),
  },
];
