import React from 'react';
import LessonShell from '../../components/LessonShell';
import { P, Def, Thm, Practice } from '../../components/LessonBody';
import { InlineMath, BlockMath } from 'react-katex';
import SoftmaxViz from '../../viz/2d/SoftmaxViz';

export default function Lesson9_2() {
  return (
    <LessonShell lessonId="llminfra-9-2">
      <div className="space-y-6">
        <P>
          The softmax is an innocuous line of code — three instructions in PyTorch. It is also a
          smooth diffeomorphism from <InlineMath math="\mathbb{R}^n / \mathbb{R} \mathbf{1}" />
          {' '}to the open probability simplex, with a convex log-partition, a Bregman geometry,
          and a temperature knob that moves continuously between center-of-mass and argmax. Every
          sampling, routing, and gating decision in an LLM lives on this surface.
        </P>

        <Def title="Softmax as Gibbs distribution">
          For logits <InlineMath math="z \in \mathbb{R}^n" /> and inverse temperature{' '}
          <InlineMath math="\beta \ge 0" />,
          <BlockMath math="p_i = \frac{e^{\beta z_i}}{\sum_j e^{\beta z_j}} = \frac{e^{\beta z_i}}{Z(\beta, z)}." />
          This is the Gibbs distribution with "energy" <InlineMath math="-z_i" /> and
          "temperature" <InlineMath math="1/\beta" />. The log-partition{' '}
          <InlineMath math="A(\beta z) = \log \sum_j e^{\beta z_j}" /> is the same convex
          function we met in the exponential-family lesson (§7.4).
        </Def>

        <Thm
          title="Softmax is the gradient of log-sum-exp"
          proof={
            <>
              Differentiate <InlineMath math="A(z) = \log \sum_j e^{z_j}" /> w.r.t.{' '}
              <InlineMath math="z_i" />:{' '}
              <InlineMath math="\partial_i A = e^{z_i} / \sum_j e^{z_j} = p_i" />. So
              <InlineMath math="\nabla A = \mathrm{softmax}(z)" />; convexity of{' '}
              <InlineMath math="A" /> (its Hessian is <InlineMath math="\mathrm{diag}(p) - p p^\top \succeq 0" />)
              gives uniqueness and smoothness of the map.
            </>
          }
        >
          <InlineMath math="\mathrm{softmax}(z) = \nabla \log \sum_j e^{z_j}" />. The map is a
          diffeomorphism from <InlineMath math="\mathbb{R}^n / \mathbb{R} \mathbf{1}" /> onto the
          open simplex <InlineMath math="\Delta^{n-1}" />, with Jacobian{' '}
          <InlineMath math="\mathrm{diag}(p) - p p^\top" /> — the Fisher information metric of
          the categorical family.
        </Thm>

        <div className="py-2"><SoftmaxViz /></div>

        <Def title="Temperature limits">
          As <InlineMath math="\beta \to 0" />, softmax → uniform distribution (maximum entropy).
          As <InlineMath math="\beta \to \infty" />, softmax → argmax (a one-hot at the unique
          top logit; tied logits yield a tied limit). The cross-entropy loss{' '}
          <InlineMath math="-\log p_y" /> at <InlineMath math="\beta = 1" /> is the
          Bregman divergence generated by <InlineMath math="A" />.
        </Def>

        <Thm title="Top-k, top-p, and truncated support">
          Top-<InlineMath math="k" /> sampling restricts to the top <InlineMath math="k" />{' '}
          logits; top-<InlineMath math="p" /> (nucleus) keeps the smallest prefix whose
          probability mass exceeds <InlineMath math="p" />. Both are projections of the softmax
          onto a face of the simplex, preserving relative ratios within the kept set.
        </Thm>

        <Practice>
          <strong>Sampling temperature</strong> is the knob everyone turns — it literally IS{' '}
          <InlineMath math="1/\beta" /> of this softmax. <strong>MoE routing</strong>{' '}
          (Shazeer, Switch Transformer, Mixtral) uses a softmax over expert logits, often with
          top-<InlineMath math="k" />-routing to enforce sparsity; the "router loss" is exactly
          the entropy of this softmax over experts. <strong>RLHF</strong> policy distributions
          are softmaxes whose logits are shifted by a learned reward; KL penalties between
          trained and reference softmax distributions live on the simplex geometry described
          above. <strong>Gumbel-softmax</strong> and <strong>straight-through estimators</strong>
          are reparameterization tricks that differentiate through the{' '}
          <InlineMath math="\beta \to \infty" /> argmax.
        </Practice>
      </div>
    </LessonShell>
  );
}
